name: liquid_clock
description: Liquid clock.
version: 1.0.0+1

environment:
  sdk: '>=2.5.2 <3.0.0'
analyzer:
  enable-experiment:
    - control-flow-collections

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Fruktur
      fonts:
        - asset: fonts/fruktur-regular.ttf
